In [2]:
import numpy as np
novo_array = np.array([1,2,3])
type(novo_array)

numpy.ndarray

In [4]:
type(novo_array[0])

numpy.int64

In [6]:
# menor infinito
-np.inf
# maior infinito
+np.inf

inf

##Infinito


In [7]:
meu_array = np.array([1,2,3,4,5,6,7,9,8])
meu_array[2:6]

array([3, 4, 5, 6])

In [14]:
#Array de 1
one = np.ones(3)
one

zeros = np.zeros(3)
zeros

random_valores = np.random.random(3)
random_valores

random_valores_10 = np.random.random(3) * 10
random_valores_10

array([8.15193333, 2.87625087, 9.48388667])

In [16]:
#soma, subtração, multiplicação e divisão
data = np.array([1,2,3,4])
print(data)

ones = np.ones(4, dtype = int)
print(ones)

data - ones

[1 2 3 4]
[1 1 1 1]


array([0, 1, 2, 3])

In [17]:
data / ones

array([1., 2., 3., 4.])

In [19]:
#agregação
data = np.random.random(10)
data.max()

0.8453344748930781

In [20]:
data.min()

0.04426405927737054

In [21]:
data.sum()

5.158696693248475

In [22]:
data = np.array([1,2,3,4,5])
data.cumsum()
# soma acumulada

array([ 1,  3,  6, 10, 15])

In [23]:
# mediana
np.median(data)

3.0

In [24]:
#Desvio padrão -> o quanto um valor se distancia da média
#standart deviantion
np.std(data)

1.4142135623730951

In [27]:
array = np.array([])

for i in range(10):
    array = np.append(array, i)

array

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Faça uma função que receba uma string e retorne um array numpy contendo os caracteres dessa string.
Uma das primeiras obras muldialmente publicadas de Dan Brown, autor do famoso `Código Da Vinci`, é o livro Fortaleza Digital. Neste livro, a personagem principal, Suzan Fletcher, é uma criptógrafa da NSA (National Security Agency). No livro, a personagem descreve como criar uma criptografia de forma simples :
 - 1. Substitua cada letra do alfabeto por um número. Assim, A = 1, B = 2, C = 3 e assim por diante. Logo a palavra ADA pode ser representada por 121.
- ADA => A = 1
            D = 4
            A = 1

- 2. Para cada letra da palavra que deseja encriptar adicione 1. 
 - ADA => A = 1 + 1 = 2 --> B
          D = 4 + 1 = 5 --> E
          A = 1 + 1 = 2 --> B
 - Assim, a palavra ADA, codificada seria BEB.
- 3. Para decriptar, basta fazer o processo inverso. Representando cada letra da palavra codificada como número, subtraindo 1 e mapeando para a letra correspondente. 
 
 Faça um programa que receba uma entrada e aplique a criptografia como mostrada acima.<br>
> Obs.: Considere os valores de cada letra como os valores da tabela ascii.